version: '3.5'

services:

  rbacmanagement-mongodb:
    build:
      context: ${BASE_IMAGES_FOLDER}/mongodb/
      args:
        init_file: ${MONGO_INIT_FILE}
    image: rbacmanagement-mongodb
    container_name: rbacmanagement-mongodb
    ports:
      - "27019:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    volumes:
      - volrbacmanagement-mongodb:/data/db
    networks:
      - rbacmanagement-network

volumes:
  volrbacmanagement-mongodb:

networks:
  rbacmanagement-network:
    name: rbacmanagement-network
    driver: bridge