version: '3.5'

services:
  mysql:
      image: mysql:8.0.19
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
  keycloak:
      image: jboss/keycloak
      environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: alfa1beta2@
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
      ports:
        - 8080:8080
      depends_on:
        - mysql

volumes:
  mysql_data:
      driver: local