version: '3.5'

services:
  
  server-tls:
    build: ./server
    image: server-tls
    container_name: server-tls
    command: npm start
    ports:
     - 0.0.0.0:8443:8443
    environment:
      PORT: 8443
      KEY: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIJKQIBAAKCAgEAsVsPodPgG+HbKyoyUV6XkxT0z9pwp9+xd1uWQqGLt6CSM4V1
        i78O/NkGbEaiTfyE+XYCkK/m2P2l3HiXyYcAo4GNfM5e1+uHUeaYqOLtIMdBDTmg
        Xf2Ir90Tyshp9bOnfvm9tJmkruy0mPAqiGliRw4VdhjlQB02Rr7zDbj26967q2ce
        bJEHQf6zw+UE7xFtL7VZjvqyPHOsWaHXAKdikSn/n00ahz5Um5KIRly5VS60vpPn
        wCAdnfu1X32lSfYifAvj65oiBRBierShctZki/Fcsp5HO6daHWdVIWMTxvzx7Gnr
        yJ7hcGTdDC1VvJMX01fwnzQqFCHddc7ld48MnEiqaY61od1Jk0Gdy+C8r+44qYpM
        fxF6sESY3FdtC2eFeW1mSs4XaL8l46XaCOz5mNOmWVebCSjPo6Lh+p4cIUutTRtD
        /PBRcLnX2Z017YIQWHMLxDty8GqMiwzehWefHjtCAbqTvkCr0E0PsYob3vo7pr8W
        TKDFIpdbxnornJutWP6/AKD8tRwJZUgQpmunlXzNwP5gaWNmtZGEJxcom7Lo8zdv
        U+ZaZzAFeriP+Me5aWv0nSLU8JncKY/Ct8+5jZgl4thDf3CeHCO5Ui1XonO9x6ev
        9jMu8/O9MhbZO5n4VPsRKfLBJp6XThhLG7F/CpzEgjf0/UOqeVpvPLIq5zUCAwEA
        AQKCAgBwY14ilJs90AAM+G5uddzjjbIdTTV6jBxvoJA1pR1evdgn4fi9F9OtkvGp
        B5GujcjONGQnv/AvrXy/m4PEZ1KWSnCYmEYt2ckks1YmH7dYwCuO7+eZ6CIIH7Z9
        GEddNf18T1JR8dMULle7WuX5D58BnAEpl1kfKePNLQ/ksEN48OpIEc6LydOplHfi
        OWzI+mgQhYE9Q8xS1pJvMkmG1ot1pgGgt0GKVotTEqZcwEGJo1FSO3Puoetiw7EJ
        1Bs8JUdxCC/kiwXn45wkWfa9SPLqY4b0gaxuNvy6CVM/FwPfY0cDI5QQy+3cRW52
        WvwrxaKhgOawXGQV4efu0a9D9lhsWt59Mnsu82t5Ugwn5FPMMcgf2T8kqf+0e5Ze
        7H8dJOK8zk4HT5kjmaBb4Q6Nz+9Re3kC1hN5WZMZ4VfljN2Iuq8C+4oDqFJtStxh
        v/++tb9coDolV0w38xAz5S09dbyUu+ESD28aCdg7M7Er+BTwTFURqqsM11jQ1a7O
        WMBhczDB/jEqIkg4PKEq1b0D3eeCF63sfXyN4u2l0ml4i/bhmNIvx6Mwl8s7skCC
        M1ht6k9DybPBg0YIha4xMZv6r/h74m9yx4g/SNRBhIzfY3kWFZ4HAVg8A6WiUOaw
        YX555IIwn2WALjzQrp5EQ3C9ZjPfuIa2158iUdwM7mM5aKEzOQKCAQEA2OqEun24
        KKd57nS7INw9Wv8/ERyuyNNLYCfEvG6XJSAovIWJUQ78R/KQgAMltfx1/JOytZ4Y
        NK2815egRjLWBXQiMJqFD6sKRQuqv7RPaTpka3op3OxmadWdWbIXe/XertNnF6J/
        gmjAYEbF4uOtAMAxmEPluNrS7lpCrBrZOBhvolmHyS2KbPOIi8PsfWTc0d99ccJv
        v8H0CC74BBbjGWgot61PL2Al2lVi73rc+YnMYlgowze4vUvvydbS4Lz+Ifayrb2v
        VwQp7Biwbk/6BrdfrKD7bjpjAj0dRv1XYCdeH2ZE+drUMwRhGvP4sKwvq66hVBPZ
        pWoIlZwUZF4GhwKCAQEA0U/HVVgX+HMGPk3N9qEWqCfvvD9SxfU1Txb+KqHh0nqb
        ukqvIjgHWvsfXBHMv9b+2TovsZG8lpsq205z6Gsm53GiSh1sE8A35WhUz1HEO2RV
        AfE2c2AqUFr2/K5Xr7UqvD4wzlsf/YFTohjMbgwFI/hOxlwZ7+GuHhqHcc6rU5cl
        5mf121U/Y/WmvmV/Hk7zgQa48b2mmRsK8InYVcgsHnEkfENRUU5Wmrz5LMQtTqdC
        o7UEhghHlQRd0pzONmkKCaL0/vKbN3naZM8Me9Md6VtLw8hRIXuAS/KnZVxSFBc6
        uopQHs2yRv1W4V+Qb9uogO5VLqbNI/BjGApzpNXXYwKCAQEAhaXBD5JENDAz7RrY
        7P8lgnp/phBxFGUzLNRz39GXqJUu5DC2kU3VXJL0Oxs1UfJx06RA2KvGqDZfgsn2
        QyoxOXz7T8z0rNmqYy40DxeOUfxbQOks/+RbmVu3LjuPQp4TjM3N1/8T5wqZdPhG
        FmxG/I5uQC2dTY7tpVPRfm6wZWKQ7YuSIP7BKi3GdK7Ld9r8PwcfKEcvSQu8Sop9
        3y8mz1GgvMK4Zi0sRWCUq46ctdcUKYe93cHoPiGaZVbJ6RQo1E5GesvDS67SEZiI
        o/78wsSa2yb4o0qwFAIJluKiwiifUmNVnkgYtDI/jjbBhEEiwfm/hqkQUV2KWnun
        CMvx4wKCAQEAjo7jmMDzMohFDFI5oWx93fG1WmVWnvUvZbqnSaoQACb5wZv0RD4c
        5F59MVv+M/regF0c9rfn1jvAqLV6RCYWzTOb8Raw8ZLNfzXb7YgnOrxPGY+MInCw
        4SHTbq3fkxC1FpjU7PcrhqF6sMBrG9ib96+7F2bLU5JF4ML41Q6JqdkcOx07WjNp
        hU9eTfca6S2ks5A8jok42raMcN+xtFstkV5GF0xSKipM2f8zRsYmhZdtz8oOVqt0
        9Y2PyU57NJu99mpCqxHZnaMkl9xdCEj16mX/6Eya1U8kRpXyZRrH3F8l5L8napN2
        hNsvPTi1Szo0PfwVkDyTI5MqKsmTkgUDOQKCAQAkIktms8uzIwcwVVTw8StSEqqu
        rrjx8+ImqMbEQewKeIQHxB1/qUHp5bZlNfwvPcHjrMmdX28N5/VI/BODzrR1Xzk1
        aFSycHEcvEtLNu7uOY0vtOLkfmWwBuPGz4UmHKL9Fo5GwsFqq3IR5K351vrx6bKj
        eac29ucSiyiSeY/nuYlcgIDN3sCAieBGS5iOgHXjRjGL9fuRmOeLJni9J4NFgCqI
        oqYvmJNnTOWs1IILSS9DamvQA+55VO4/0YG5Zq4aR/R6ttvEbHJRh1ZQTxF3bzvm
        EyRwpBBZQE/qA/MtOWvNHQfRtBk97XWTeQdjjbSqX3vEiTc8aG4m8Cxw/FO8
        -----END RSA PRIVATE KEY-----
      CERT: |
        -----BEGIN CERTIFICATE-----
        MIIFmDCCA4CgAwIBAgIUQAa7oZL6hp4ZTnurQ4EpU7h42pIwDQYJKoZIhvcNAQEL
        BQAwgYExCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJNQTEPMA0GA1UEBwwGQm9zdG9u
        MRMwEQYDVQQKDApFeGFtcGxlIENvMRAwDgYDVQQLDAd0ZWNob3BzMQswCQYDVQQD
        DAJjYTEgMB4GCSqGSIb3DQEJARYRY2VydHNAZXhhbXBsZS5jb20wHhcNMjAwNjAx
        MTc0NTQ1WhcNMjMwMjI1MTc0NTQ1WjCBiTELMAkGA1UEBhMCVVMxCzAJBgNVBAgM
        Ak1BMQ8wDQYDVQQHDAZCb3N0b24xEzARBgNVBAoMCkV4YW1wbGUgQ28xEDAOBgNV
        BAsMB3RlY2hvcHMxEzARBgNVBAMMCnNlcnZlci10bHMxIDAeBgkqhkiG9w0BCQEW
        EWNlcnRzQGV4YW1wbGUuY29tMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
        AgEAsVsPodPgG+HbKyoyUV6XkxT0z9pwp9+xd1uWQqGLt6CSM4V1i78O/NkGbEai
        TfyE+XYCkK/m2P2l3HiXyYcAo4GNfM5e1+uHUeaYqOLtIMdBDTmgXf2Ir90Tyshp
        9bOnfvm9tJmkruy0mPAqiGliRw4VdhjlQB02Rr7zDbj26967q2cebJEHQf6zw+UE
        7xFtL7VZjvqyPHOsWaHXAKdikSn/n00ahz5Um5KIRly5VS60vpPnwCAdnfu1X32l
        SfYifAvj65oiBRBierShctZki/Fcsp5HO6daHWdVIWMTxvzx7GnryJ7hcGTdDC1V
        vJMX01fwnzQqFCHddc7ld48MnEiqaY61od1Jk0Gdy+C8r+44qYpMfxF6sESY3Fdt
        C2eFeW1mSs4XaL8l46XaCOz5mNOmWVebCSjPo6Lh+p4cIUutTRtD/PBRcLnX2Z01
        7YIQWHMLxDty8GqMiwzehWefHjtCAbqTvkCr0E0PsYob3vo7pr8WTKDFIpdbxnor
        nJutWP6/AKD8tRwJZUgQpmunlXzNwP5gaWNmtZGEJxcom7Lo8zdvU+ZaZzAFeriP
        +Me5aWv0nSLU8JncKY/Ct8+5jZgl4thDf3CeHCO5Ui1XonO9x6ev9jMu8/O9MhbZ
        O5n4VPsRKfLBJp6XThhLG7F/CpzEgjf0/UOqeVpvPLIq5zUCAwEAATANBgkqhkiG
        9w0BAQsFAAOCAgEAqkKhfB4ukpQ0vVdKl6YMJ8mRHIKN1PwTUpmDxoezrBKlFZCO
        ZI7fAjyHvEKKrpVSm0FP1NzN2t/HzHmN+cxy5Ta5au/6Whin2d4IedbtBd8DJIeK
        +O9NNRmngqTezYPzL0AdpvoxJxz3PZoLbBuHVhxlYwy1gbATON6ukK4+6ivHM8Pd
        guq+9f1klNz9kRIH76+plmIj7LpOAw9xS3ohygC0z775yuOf8q9yYUwMikCpEZr7
        NJ+PRImeEbZ9TcclPCosgtpSGqWzIMcPRFKFaw6GA26t4M75va/3AyPqARxkvJN2
        bf6Rirr4rwCkziRw9orZPsSLEdMjPeR2nrqixWSI9toeIsOkq6BJN9R6ygQyjU0E
        Wity0j8Mfj1kr5/PPV+j9QJjVVJdN8JF4/w4VvjEQhv+hlpe2ncXXsCA2rQaV9/0
        a+tdbqaOhiW3GZwRZhHEic+tqWl7Oskbt5g3vRlTffVsBw9L8ciK8inN6ifRUTnS
        ACX0sdNFDlo+SA+nZAM8nxxADLTzNeJdHgg7PZacV65uxkzPrTrKOko1JrgHp3qB
        Y1dhR3BM4qEq9I434Uk7jnOJwyGnUbfYBjOElFC4b/le6K3exwKI6IdDRTMcPcqI
        udUB3L1yUZiv4UNH5iosd/ySr4Auvb0gAH8k69h78WvC6xxwCB+1xYcLfqc=
        -----END CERTIFICATE-----
      CA: |
        -----BEGIN CERTIFICATE-----
        MIIFizCCA3MCFG6HPPY/m+9AXHwr9jJ67l5vF2zdMA0GCSqGSIb3DQEBCwUAMIGB
        MQswCQYDVQQGEwJVUzELMAkGA1UECAwCTUExDzANBgNVBAcMBkJvc3RvbjETMBEG
        A1UECgwKRXhhbXBsZSBDbzEQMA4GA1UECwwHdGVjaG9wczELMAkGA1UEAwwCY2Ex
        IDAeBgkqhkiG9w0BCQEWEWNlcnRzQGV4YW1wbGUuY29tMB4XDTIwMDYwMTE3MTg0
        MFoXDTQ3MTAxNzE3MTg0MFowgYExCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJNQTEP
        MA0GA1UEBwwGQm9zdG9uMRMwEQYDVQQKDApFeGFtcGxlIENvMRAwDgYDVQQLDAd0
        ZWNob3BzMQswCQYDVQQDDAJjYTEgMB4GCSqGSIb3DQEJARYRY2VydHNAZXhhbXBs
        ZS5jb20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDDMC6D5WfeCBnO
        j/fy08LG7hag+zBK8nJUyjypDFsicd3evHJJqyoqVi76dHqB3H+jo9bxjmEeRtAP
        G+EB7dS1YGX5BUzlfQUMZUG45cXFaACo38DRcPvHuqcIAEsom5X+AxJcnZaDIDv4
        yTicFNPucGjv9PJYDIG4X1CCGgRUw7wnMw1bKn1ddr/Sq5G3N60GFqv6waXccOCN
        i7XbwK8jdw0WL9TipiGRSZJBFWt1wMSEm6KciOn8VhqMOI4i/mMs84rvf9XW2lie
        6kUqMjmh8AUXL3RYeXqTLpz7pwSS0ecEZoZ0iPBNVn4HYa4vDRmQihFimwXnfrK9
        aKdLqXS2oV9h8D+6DI46zR6sI+zHwl3WfTVtXMgAsu74dnLUVOeKL4klHfxXBM+k
        hR/oy9RBjTpLZPCu/J2OsP66SwhjR+7X34wrqIUw3L+uPO55DHLZ43sLvEhtggHo
        BSPwu8kxyEn9Rr1rUs5A0HzrbIN2YUsmrqI+BLRRWjf26KGIgedOtJqQ1hAXwZlj
        ZnxgVIStfVg5QrzGTmSxviJNOsbDETLUUpK61SH1is5peAqyyzvT1pKe6yNriU4t
        mRYw56ZT8l6+feFbrwwFw7Eeo/nmctwrGo9cfx/7igtp2ksOGgN2fQHRD/L/itxI
        Y3dPGjfC/5kiuT5P4ilkq1w+BnX6nQIDAQABMA0GCSqGSIb3DQEBCwUAA4ICAQAX
        MNHb06jwW7WyvsFvH1kiL91UacKijxlThYs1otpj/NtU3U3hvq1La6UZAKIeO7Am
        kKxVTWmYiJR1o3mqjZTLzuBSmHPPrbykVflC4pySm871DkloZGsHQ1frUD5XKjka
        IRop9+MevY5i3RiYxwVgTtSSDZ0rLsxzM7mTzmGe0XU0RgPB2jxnzTFYaN2M9HwY
        xGIjAyq7aizdYunOTBpNrBrmXpRl6g8fE1G5mIiEw5OuCAD7hxz8tLpDlYU2QtJw
        5Ai6MwpxWOgv+v6rJq6mrvpxO1tOwCNO9FM9fPIk+Uj5la/u+oLNvMbeo32LwVxF
        f7B4oEwpEO4RT+ugRDyzfSc+8jhdt8lMkDmAaHllnxFoHCTkQWC7GAhIm1ElmPUu
        hsnTjSMnbV/GYrwYpBF6bKH3fJtmBVmAzKeR9jZPt6kn/MU7LnG+jc5LNdnqtCDm
        HMTD4HfE2lzgfrFfobRFCXrCNExF64DPZzljYAizztRouEvKQdLqcjwx1T/4Vp6n
        3fGCnmEutIcTgi7LLpSeG6PrK+AZoRBfiI9mzatfu++gEJOEA8sVPWQ6sqaN/VB0
        tUiUw01SCsaaeBvz+647LtvjZBYEe7kGZTuGXuDJW/CYtT34keCWJ4i3tT5uxlSp
        EdAfGQNKTF8hneVF8S5x7MYlAPchzmWrWxUYu1Mrkg==
        -----END CERTIFICATE-----

    networks:
      - test-tls

  client-tls:
    build: ./client
    image: client-tls
    container_name: client-tls
    command: npm start
    environment:
      ENDPOINT: https://server-tls:8443/hellotls
      CA: |
        -----BEGIN CERTIFICATE-----
        MIIFizCCA3MCFG6HPPY/m+9AXHwr9jJ67l5vF2zdMA0GCSqGSIb3DQEBCwUAMIGB
        MQswCQYDVQQGEwJVUzELMAkGA1UECAwCTUExDzANBgNVBAcMBkJvc3RvbjETMBEG
        A1UECgwKRXhhbXBsZSBDbzEQMA4GA1UECwwHdGVjaG9wczELMAkGA1UEAwwCY2Ex
        IDAeBgkqhkiG9w0BCQEWEWNlcnRzQGV4YW1wbGUuY29tMB4XDTIwMDYwMTE3MTg0
        MFoXDTQ3MTAxNzE3MTg0MFowgYExCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJNQTEP
        MA0GA1UEBwwGQm9zdG9uMRMwEQYDVQQKDApFeGFtcGxlIENvMRAwDgYDVQQLDAd0
        ZWNob3BzMQswCQYDVQQDDAJjYTEgMB4GCSqGSIb3DQEJARYRY2VydHNAZXhhbXBs
        ZS5jb20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDDMC6D5WfeCBnO
        j/fy08LG7hag+zBK8nJUyjypDFsicd3evHJJqyoqVi76dHqB3H+jo9bxjmEeRtAP
        G+EB7dS1YGX5BUzlfQUMZUG45cXFaACo38DRcPvHuqcIAEsom5X+AxJcnZaDIDv4
        yTicFNPucGjv9PJYDIG4X1CCGgRUw7wnMw1bKn1ddr/Sq5G3N60GFqv6waXccOCN
        i7XbwK8jdw0WL9TipiGRSZJBFWt1wMSEm6KciOn8VhqMOI4i/mMs84rvf9XW2lie
        6kUqMjmh8AUXL3RYeXqTLpz7pwSS0ecEZoZ0iPBNVn4HYa4vDRmQihFimwXnfrK9
        aKdLqXS2oV9h8D+6DI46zR6sI+zHwl3WfTVtXMgAsu74dnLUVOeKL4klHfxXBM+k
        hR/oy9RBjTpLZPCu/J2OsP66SwhjR+7X34wrqIUw3L+uPO55DHLZ43sLvEhtggHo
        BSPwu8kxyEn9Rr1rUs5A0HzrbIN2YUsmrqI+BLRRWjf26KGIgedOtJqQ1hAXwZlj
        ZnxgVIStfVg5QrzGTmSxviJNOsbDETLUUpK61SH1is5peAqyyzvT1pKe6yNriU4t
        mRYw56ZT8l6+feFbrwwFw7Eeo/nmctwrGo9cfx/7igtp2ksOGgN2fQHRD/L/itxI
        Y3dPGjfC/5kiuT5P4ilkq1w+BnX6nQIDAQABMA0GCSqGSIb3DQEBCwUAA4ICAQAX
        MNHb06jwW7WyvsFvH1kiL91UacKijxlThYs1otpj/NtU3U3hvq1La6UZAKIeO7Am
        kKxVTWmYiJR1o3mqjZTLzuBSmHPPrbykVflC4pySm871DkloZGsHQ1frUD5XKjka
        IRop9+MevY5i3RiYxwVgTtSSDZ0rLsxzM7mTzmGe0XU0RgPB2jxnzTFYaN2M9HwY
        xGIjAyq7aizdYunOTBpNrBrmXpRl6g8fE1G5mIiEw5OuCAD7hxz8tLpDlYU2QtJw
        5Ai6MwpxWOgv+v6rJq6mrvpxO1tOwCNO9FM9fPIk+Uj5la/u+oLNvMbeo32LwVxF
        f7B4oEwpEO4RT+ugRDyzfSc+8jhdt8lMkDmAaHllnxFoHCTkQWC7GAhIm1ElmPUu
        hsnTjSMnbV/GYrwYpBF6bKH3fJtmBVmAzKeR9jZPt6kn/MU7LnG+jc5LNdnqtCDm
        HMTD4HfE2lzgfrFfobRFCXrCNExF64DPZzljYAizztRouEvKQdLqcjwx1T/4Vp6n
        3fGCnmEutIcTgi7LLpSeG6PrK+AZoRBfiI9mzatfu++gEJOEA8sVPWQ6sqaN/VB0
        tUiUw01SCsaaeBvz+647LtvjZBYEe7kGZTuGXuDJW/CYtT34keCWJ4i3tT5uxlSp
        EdAfGQNKTF8hneVF8S5x7MYlAPchzmWrWxUYu1Mrkg==
        -----END CERTIFICATE-----

    networks:
      - test-tls

networks:
  test-tls:
    name: test-tls
    driver: bridge
      