appName: User Management
description: User Management - Express Open API - OAS 3 - N Layer
environment: dev
infrastructure:
  logger:
    level: debug
  express:
    servertimeout: 60000 #miliseconds
    port: 8080
    enableCors: true