version: '3.5'

services:

  mongodb:
    image: mongo:4.4.4
    container_name: minimalcrud-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - minimalcrud-mongodb:/data/db
    networks:
      - minimalcrud-network

volumes:
  minimalcrud-mongodb:

networks:
  minimalcrud-network:
    name: minimalcrud-network
    driver: bridge