appName: User Management
description: User Management - Express Open API - OAS 3 - N Layer
environment: dev
infrastructure:
  logger:
    level: debug
  express:
    servertimeout: 60000 #miliseconds
    port: 8080
    enableCors: true
  mongo:
    mongoURL: mongodb://admin:admin@localhost:27018
    database: usermanagementDB
    reconnectTime: 20000 #miliseconds