---
swagger: '2.0'
info:
  title: Swagger UI Helloworld
  description: Swagger UI Helloworld
  version: 1.0.0
host: localhost:8080
basePath: "/"
schemes:
- http
paths:
  /helloworld:
    x-swagger-router-controller: main.controller
    get:
      operationId: hello
      summary: Hello World
      description: Hello World
      produces:
      - application/json
      responses:
        '200':
          description: OK
